Addling line height in configuration
jobandtalent/AnimatedTextInput pull request #80
Opened 2017-10-19 08:35 UTC by Alexookah

2017-10-19 08:36 UTC, Alexookah commented
#78

2017-11-30 19:43 UTC, victorBaro requested changes
Fix a couple of issues before being able to merge. Thank you for your PR!

2017-11-30 19:43 UTC, victorBaro commented on AnimatedTextInput/Classes/AnimatedTextInput.swift
> +        lineView.setHeight(to: style.lineHeight)
Remove `lineWidth` let declared on top of the file

2017-11-30 19:43 UTC, victorBaro commented on AnimatedTextInput/Classes/AnimatedTextInputStyle.swift
> +    public let lineHeight: CGFloat = 1.0
Please use: 
`public let lineHeight: CGFloat = 1.0 / UIScreen.main.scale` to maintain original value.

2017-11-30 21:12 UTC, Alexookah commented
thanks for your feedback. somehow my repository with my latest pull request were removed. so thats why i made a new pull request with these changes check it

2017-12-01 11:03 UTC, Alexookah commented
see the new reuqest https://github.com/jobandtalent/AnimatedTextInput/pull/89

2017-12-01 11:03 UTC, closed without merging